# Generated by Django 2.0 on 2019-12-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websecurityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('borrador', models.BooleanField()),
                ('vetada', models.BooleanField()),
                ('motivoVeto', models.CharField(max_length=1000)),
                ('fechaCreacion', models.DateField()),
                ('comentable', models.BooleanField()),
                ('identificador', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=30)),
                ('empresaUEquipo', models.CharField(max_length=100)),
                ('vetado', models.BooleanField()),
                ('esAdmin', models.BooleanField()),
                ('django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='anexo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websecurityapp.Usuario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websecurityapp.Usuario'),
        ),
    ]
