# Generated by Django 2.0 on 2019-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websecurityapp', '0002_auto_20191225_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='identificador',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
