# Generated by Django 3.0.2 on 2020-01-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websecurityapp', '0007_auto_20200106_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='motivo_veto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa_u_equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
