# Generated by Django 3.0.2 on 2020-01-07 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websecurityapp', '0008_auto_20200106_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='No sigue el patron', regex='^(\\+\\d{1,3}\\(\\d{1,3}\\)*)*\\d{4,}$')]),
        ),
    ]
