# Generated by Django 3.0.2 on 2020-02-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websecurityapp', '0009_auto_20200107_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websecurityapp.Actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websecurityapp.Usuario')),
            ],
        ),
    ]
